# Gradle
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC
org.gradle.configuration-on-demand=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true

# Kapt
kapt.incremental=true
kapt.use.worker.api=true

# Android
android.useAndroidX=true
android.enableJetifier=true
android.compileSdkVersion=34
